/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as appAppImport } from './routes/(app)/_app'
import { Route as authRegisterIndexImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexImport } from './routes/(auth)/login/index'
import { Route as authEmailConfirmedIndexImport } from './routes/(auth)/email-confirmed/index'
import { Route as authEmailConfirmationIndexImport } from './routes/(auth)/email-confirmation/index'
import { Route as appAppChatsIndexImport } from './routes/(app)/_app/chats/index'
import { Route as appAppChatsChatIdRouteImport } from './routes/(app)/_app/chats/$chatId/route'
import { Route as appAppChatsNewIndexImport } from './routes/(app)/_app/chats/new/index'
import { Route as appAppChatsChatIdIndexImport } from './routes/(app)/_app/chats/$chatId/index'

// Create Virtual Routes

const appImport = createFileRoute('/(app)')()

// Create/Update Routes

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appAppRoute = appAppImport.update({
  id: '/_app',
  getParentRoute: () => appRoute,
} as any)

const authRegisterIndexRoute = authRegisterIndexImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginIndexRoute = authLoginIndexImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const authEmailConfirmedIndexRoute = authEmailConfirmedIndexImport.update({
  id: '/(auth)/email-confirmed/',
  path: '/email-confirmed/',
  getParentRoute: () => rootRoute,
} as any)

const authEmailConfirmationIndexRoute = authEmailConfirmationIndexImport.update(
  {
    id: '/(auth)/email-confirmation/',
    path: '/email-confirmation/',
    getParentRoute: () => rootRoute,
  } as any,
)

const appAppChatsIndexRoute = appAppChatsIndexImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppChatsChatIdRouteRoute = appAppChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => appAppRoute,
} as any)

const appAppChatsNewIndexRoute = appAppChatsNewIndexImport.update({
  id: '/chats/new/',
  path: '/chats/new/',
  getParentRoute: () => appAppRoute,
} as any)

const appAppChatsChatIdIndexRoute = appAppChatsChatIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appAppChatsChatIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_app': {
      id: '/(app)/_app'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appAppImport
      parentRoute: typeof appRoute
    }
    '/(auth)/email-confirmation/': {
      id: '/(auth)/email-confirmation/'
      path: '/email-confirmation'
      fullPath: '/email-confirmation'
      preLoaderRoute: typeof authEmailConfirmationIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/email-confirmed/': {
      id: '/(auth)/email-confirmed/'
      path: '/email-confirmed'
      fullPath: '/email-confirmed'
      preLoaderRoute: typeof authEmailConfirmedIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_app/chats/$chatId': {
      id: '/(app)/_app/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof appAppChatsChatIdRouteImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/chats/': {
      id: '/(app)/_app/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof appAppChatsIndexImport
      parentRoute: typeof appAppImport
    }
    '/(app)/_app/chats/$chatId/': {
      id: '/(app)/_app/chats/$chatId/'
      path: '/'
      fullPath: '/chats/$chatId/'
      preLoaderRoute: typeof appAppChatsChatIdIndexImport
      parentRoute: typeof appAppChatsChatIdRouteImport
    }
    '/(app)/_app/chats/new/': {
      id: '/(app)/_app/chats/new/'
      path: '/chats/new'
      fullPath: '/chats/new'
      preLoaderRoute: typeof appAppChatsNewIndexImport
      parentRoute: typeof appAppImport
    }
  }
}

// Create and export the route tree

interface appAppChatsChatIdRouteRouteChildren {
  appAppChatsChatIdIndexRoute: typeof appAppChatsChatIdIndexRoute
}

const appAppChatsChatIdRouteRouteChildren: appAppChatsChatIdRouteRouteChildren =
  {
    appAppChatsChatIdIndexRoute: appAppChatsChatIdIndexRoute,
  }

const appAppChatsChatIdRouteRouteWithChildren =
  appAppChatsChatIdRouteRoute._addFileChildren(
    appAppChatsChatIdRouteRouteChildren,
  )

interface appAppRouteChildren {
  appAppChatsChatIdRouteRoute: typeof appAppChatsChatIdRouteRouteWithChildren
  appAppChatsIndexRoute: typeof appAppChatsIndexRoute
  appAppChatsNewIndexRoute: typeof appAppChatsNewIndexRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppChatsChatIdRouteRoute: appAppChatsChatIdRouteRouteWithChildren,
  appAppChatsIndexRoute: appAppChatsIndexRoute,
  appAppChatsNewIndexRoute: appAppChatsNewIndexRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface appRouteChildren {
  appAppRoute: typeof appAppRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appAppRoute: appAppRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof appAppRouteWithChildren
  '/email-confirmation': typeof authEmailConfirmationIndexRoute
  '/email-confirmed': typeof authEmailConfirmedIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/chats/$chatId': typeof appAppChatsChatIdRouteRouteWithChildren
  '/chats': typeof appAppChatsIndexRoute
  '/chats/$chatId/': typeof appAppChatsChatIdIndexRoute
  '/chats/new': typeof appAppChatsNewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appAppRouteWithChildren
  '/email-confirmation': typeof authEmailConfirmationIndexRoute
  '/email-confirmed': typeof authEmailConfirmedIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/chats': typeof appAppChatsIndexRoute
  '/chats/$chatId': typeof appAppChatsChatIdIndexRoute
  '/chats/new': typeof appAppChatsNewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)': typeof appRouteWithChildren
  '/(app)/_app': typeof appAppRouteWithChildren
  '/(auth)/email-confirmation/': typeof authEmailConfirmationIndexRoute
  '/(auth)/email-confirmed/': typeof authEmailConfirmedIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(app)/_app/chats/$chatId': typeof appAppChatsChatIdRouteRouteWithChildren
  '/(app)/_app/chats/': typeof appAppChatsIndexRoute
  '/(app)/_app/chats/$chatId/': typeof appAppChatsChatIdIndexRoute
  '/(app)/_app/chats/new/': typeof appAppChatsNewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-confirmation'
    | '/email-confirmed'
    | '/login'
    | '/register'
    | '/chats/$chatId'
    | '/chats'
    | '/chats/$chatId/'
    | '/chats/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-confirmation'
    | '/email-confirmed'
    | '/login'
    | '/register'
    | '/chats'
    | '/chats/$chatId'
    | '/chats/new'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/_app'
    | '/(auth)/email-confirmation/'
    | '/(auth)/email-confirmed/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(app)/_app/chats/$chatId'
    | '/(app)/_app/chats/'
    | '/(app)/_app/chats/$chatId/'
    | '/(app)/_app/chats/new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRoute: typeof appRouteWithChildren
  authEmailConfirmationIndexRoute: typeof authEmailConfirmationIndexRoute
  authEmailConfirmedIndexRoute: typeof authEmailConfirmedIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRoute: appRouteWithChildren,
  authEmailConfirmationIndexRoute: authEmailConfirmationIndexRoute,
  authEmailConfirmedIndexRoute: authEmailConfirmedIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)",
        "/(auth)/email-confirmation/",
        "/(auth)/email-confirmed/",
        "/(auth)/login/",
        "/(auth)/register/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)": {
      "filePath": "(app)",
      "children": [
        "/(app)/_app"
      ]
    },
    "/(app)/_app": {
      "filePath": "(app)/_app.tsx",
      "parent": "/(app)",
      "children": [
        "/(app)/_app/chats/$chatId",
        "/(app)/_app/chats/",
        "/(app)/_app/chats/new/"
      ]
    },
    "/(auth)/email-confirmation/": {
      "filePath": "(auth)/email-confirmation/index.tsx"
    },
    "/(auth)/email-confirmed/": {
      "filePath": "(auth)/email-confirmed/index.tsx"
    },
    "/(auth)/login/": {
      "filePath": "(auth)/login/index.tsx"
    },
    "/(auth)/register/": {
      "filePath": "(auth)/register/index.tsx"
    },
    "/(app)/_app/chats/$chatId": {
      "filePath": "(app)/_app/chats/$chatId/route.tsx",
      "parent": "/(app)/_app",
      "children": [
        "/(app)/_app/chats/$chatId/"
      ]
    },
    "/(app)/_app/chats/": {
      "filePath": "(app)/_app/chats/index.tsx",
      "parent": "/(app)/_app"
    },
    "/(app)/_app/chats/$chatId/": {
      "filePath": "(app)/_app/chats/$chatId/index.tsx",
      "parent": "/(app)/_app/chats/$chatId"
    },
    "/(app)/_app/chats/new/": {
      "filePath": "(app)/_app/chats/new/index.tsx",
      "parent": "/(app)/_app"
    }
  }
}
ROUTE_MANIFEST_END */
